---
- name: Create systemd unit file for Go web server
  template:
    src: templates/systemd.j2
    dest: /etc/systemd/system/owntracks-receiver.service
    owner: root
    group: root
    mode: 0644
  notify: 
    - reload systemd units
    - restart owntracks-receiver unit

- name: Create Caddy config for owntracks.lab.tomhummel.com
  template:
    src: templates/caddy.j2
    dest: /etc/caddy/conf.d/owntracks.conf
    owner: caddy
    group: caddy
    mode: 0644
  notify: reload caddy
- name: set recursive owner permissions on directory
  file:
    path: /home/opc/owntracks-receiver/
    owner: opc
    group: opc
    mode: 0755
    recurse: yes
- name: Set SELinux file context for owntracks-receiver binary
  ansible.builtin.sefcontext:
    target: '/home/opc/owntracks-receiver/current/owntracks-receiver-linux-arm64'
    setype: 'init_exec_t'
    state: 'present'
- name: Apply SELinux file context to owntracks-receiver binary
  become: yes
  ansible.builtin.command:
    cmd: 'restorecon -v /home/opc/owntracks-receiver/current/owntracks-receiver-linux-arm64'

