---
- name: Create systemd unit file for Go web server
  template:
    src: templates/systemd.j2
    dest: /etc/systemd/system/owntracks-receiver.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd units
- name: Create Caddy config for owntracks.lab.tomhummel.com
  template:
    src: templates/caddy.j2
    dest: /etc/caddy/conf.d/owntracks.conf
    owner: caddy
    group: caddy
    mode: 0644
  notify: reload caddy
- name: set recursive owner permissions on versions directory
  file:
    path: /home/opc/
    owner: opc
    group: opc
    mode: 0755
