---
- name: Deploy Go application
  hosts: all
  become: yes
  vars:
    ansistrano_deploy_to: /home/opc/owntracks-receiver
    ansistrano_version_dir: versions
    ansistrano_current_dir: current
    ansistrano_keep_releases: 5
    ansistrano_shared_paths: []
    ansistrano_shared_files: []
  tasks:
    - name: create data directory
      file:
        path: /home/opc/data
        state: directory
        mode: '0755'
    - name: Ensure shared paths exist
      file:
        path: "{{ ansistrano_deploy_to }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ ansistrano_shared_paths }}"

  roles:
    - role: ansistrano.deploy
      ansistrano_deploy_via: download
      ansistrano_get_url: "https://github.com/tphummel/owntracks-receiver/releases/download/{{ ansistrano_release_version }}/owntracks-receiver-linux-arm64"
      ansistrano_download_force_basic_auth: false
      ansistrano_after_symlink_tasks_file: hooks/after-symlink.yml
  
  handlers:
    - name: reload systemd units
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: start owntracks-receiver unit
      ansible.builtin.systemd:
        name: owntracks-receiver
        state: started
    - name: reload caddy
      ansible.builtin.systemd:
        name: caddy
        state: reloaded