name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Download Go modules
        run: go mod download
      - name: Run Go tests
        run: go test ./...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set the current date and short Git SHA
        id: date-and-sha
        run: |
          echo "::set-output name=current_date::$(date +'%Y-%m-%d')"
          echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-5)"

      - name: Build and push multi-architecture Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/yourimagename:latest
            ghcr.io/${{ github.repository_owner }}/yourimagename:${{ steps.date-and-sha.outputs.current_date }}-${{ steps.date-and-sha.outputs.short_sha }}
